sudo: false
language: android
jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.1
    - android-25
    - extra-android-m2repository

before_install:
  - sh scripts/emulator.sh

after_script:
  - adb logcat -d